/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_ctimer.h"
#include "fsl_clock.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define CTIMER4_PERIPHERAL CTIMER4
/* Timer tick frequency in Hz (input frequency of the timer) */
#define CTIMER4_TICK_FREQ 100000UL
/* Timer tick period in ns (input period of the timer) */
#define CTIMER4_TICK_PERIOD 10000UL
/* Definition of PWM period channel. */
#define CTIMER4_PWM_PERIOD_CH kCTIMER_Match_3
/* Definition of PWM period */
#define CTIMER4_PWM_PERIOD 99
/* Definition of channel 1 ID */
#define CTIMER4_PWM_1_CHANNEL kCTIMER_Match_1
/* Definition of channel 1 duty */
#define CTIMER4_PWM_1_DUTY 0
/* Definition of channel 0 ID */
#define CTIMER4_PWM_0_CHANNEL kCTIMER_Match_0
/* Definition of channel 0 duty */
#define CTIMER4_PWM_0_DUTY 0
/* CTIMER4 interrupt vector ID (number). */
#define CTIMER4_TIMER_IRQN CTIMER4_IRQn
/* CTIMER4 interrupt vector priority. */
#define CTIMER4_TIMER_IRQ_PRIORITY 1

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const ctimer_config_t CTIMER4_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
